name: ${project.name}
version: ${project.version}
description: ${project.description}
main: ovh.excale.mc.UHC
authors:
  - Excale
  - Cr4zy5ky_U
  - dev_excale@hotmail.com
api-version: "1.18"
website: ${project.url}
load: POSTWORLD