debug: true
delWorlds: true
locale: it
faker: esports.team

discord:
  token: "TOKEN_HERE"
  guildId: 0000

uhc:
  border:
    InitialSize: 1500
    actions:

      - BorderSize: 1500
        Minutes: 5
        Action: Hold

      - Minutes: 5
        Action: Shrink
        BorderSize: 1250

      - BorderSize: 1250
        Minutes: 5
        Action: Hold

      - Minutes: 5
        Action: Shrink
        BorderSize: 1000

      - BorderSize: 1000
        Minutes: 5
        Action: Hold

      - Minutes: 5
        Action: Shrink
        BorderSize: 500

      - BorderSize: 500
        Minutes: 5
        Action: Hold

      - BorderSize: 500
        Minutes: 5
        Action: Hold

      - Minutes: 5
        Action: Shrink
        BorderSize: 350

      - BorderSize: 350
        Minutes: 5
        Action: Hold

      - Minutes: 5
        Action: Shrink
        BorderSize: 200

      - BorderSize: 200
        Minutes: 5
        Action: Hold

      - Minutes: 5
        Action: Shrink
        BorderSize: 50

      - BorderSize: 50
        Minutes: 5
        Action: Hold

      - Minutes: 20
        Action: Shrink
        BorderSize: 2