# Used case: Pascal Case / Upper Camel Case

# Misc configuration
Debug: true               # Whether to activate debug mode
DelWorlds: true           # Whether to delete used .xkuhc worlds on startup

# Faker configuration
Faker:
  Locale: "it"            # Custom Locale to use with Faker.
  Key: "esport.teams"     # TODO: hint

# Discord configuration
Discord:
  Token: "TOKEN_HERE"     # Discord bot's token
  GuildId: 0000           # The Id of the guild where the players are

# Game configuration
Game:

  # Whether friendly fire is enabled in-game
  FriendlyFire: false

  # Whether to enable repellent crafting TODO
  EnableRepellent: true

  # Whether to reset (remove) all teams after a game
  ResetAfter: true

  # Time after which logging out becomes lethal (seconds)
  LethalDisconnectTime: 1800    # 30 min

  # Border specific configuration
  Border:
    InitialSize: 1500     # Initial border size (whole square side length)
    Actions:

      # Action: <Hold|Move>
      # (Whether to move the border or leave it as is.)
      #
      # BorderSize: <Integer>
      # (Length of the whole side of the border, not from the centre.)
      # (Required only on Action=Move, the border will move to the specified size.)
      #
      # Time: <Integer>
      # (How much time to perform the action. Measured in seconds.)

      - Action: Hold
        Time: 300

      - Action: Move
        BorderSize: 1250
        Time: 300

      - Action: Hold
        Time: 300

      - Action: Move
        BorderSize: 1000
        Time: 300

      - Action: Hold
        Time: 300

      - Action: Move
        BorderSize: 500
        Time: 300

      - Action: Hold
        Time: 300

      - Action: Move
        BorderSize: 350
        Time: 300

      - Action: Hold
        Time: 300

      - Action: Move
        BorderSize: 200
        Time: 300

      - Action: Hold
        Time: 300

      - Action: Move
        BorderSize: 50
        Time: 300

      - Action: Hold
        Time: 300

      - Action: Move
        BorderSize: 2
        Time: 600